services:
  moontv:
    image: ghcr.io/senshinya/moontv:latest
    container_name: moontv
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - USERNAME=admin
      - PASSWORD=yezi
      - NEXT_PUBLIC_STORAGE_TYPE=localstorage
      - NEXT_PUBLIC_ENABLE_REGISTER=false
      - SITE_NAME=BLAZING-TV
    volumes:
      - ./config.json:/app/config.json:ro